name: Release

on:
  push:
    branches:
      - main

env:
  GRAFANA_PROJECT_ID: sync-grafana-43
  HOST_PROJECT_ID: sync-app-production-25
  GAR_LOCATION: us-central1
  CLUSTER_NAME: sync-grafana-cluster
  DEPLOYMENT_NAME: sync-grafana
  ZONE: us-central1-a
  REPOSITORY: sync-grafana
  IMAGE: grafana
jobs:
  release-production:
    runs-on: ubuntu-latest
    name: Release Superset in production

    steps:
      - name: Checkout latest version
        uses: actions/checkout@v3

      - id: auth
        name: Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
          token_format: "access_token"

      - name: Google Cloud SDK and kubectl setup
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: "kubectl, gke-gcloud-auth-plugin"

#      - name: Kubernetes Credentials
#        run: gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.ZONE }} --project ${{ env.HOST_PROJECT_ID }}

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: "${{ env.GAR_LOCATION }}-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Build and push superset image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GRAFANA_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GRAFANA_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest

#      - name: Restart Kubernetes deployment
#        run: kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.GRAFANA_PROJECT_ID }}